<a href="https://colab.research.google.com/github/lvarshitha7/ML-Lab/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



--**ML Lab using kaggle by the own dataset of placements.csv**



In [ ]:
import pandas as pd
df=pd.read_excel('/content/cgpa.xlsx')
df['Result']=df['CGPA'].apply(lambda x: "Placed" if x>8 else "Not Placed")
print(df[['Rollno','Result']])

  Rollno      Result
0     x0      Placed
1     x1      Placed
2     x2      Placed
3     x3  Not Placed
4     x4      Placed
5     x5      Placed
6     x6  Not Placed
7     x7  Not Placed
8     x8  Not Placed
9     x9      Placed


#--**Titanic dataset**


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
df=pd.read_csv('/train_and_test2.csv')
x=df[['Age']]
y=df['2urvived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
print("Mean Squared Error:",mse)

Mean Squared Error: 0.17367042744605332


#--**Decision Tree**


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
df=pd.read_csv('/x0dataset.csv')
le=LabelEncoder()
le_weather = LabelEncoder()
le_mood = LabelEncoder()
le_budget = LabelEncoder()
le_friends = LabelEncoder()
le_result = LabelEncoder()
df['Weather'] = le_weather.fit_transform(df['Weather'])
df['Mood'] = le_mood.fit_transform(df['Mood'])
df['Budget'] = le_budget.fit_transform(df['Budget'])
df['Friends'] = le_friends.fit_transform(df['Friends'])
df['Result'] = le_result.fit_transform(df['Result'])
x=df[['Weather','Mood','Budget','Friends']]
y=df['Result']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
test=[[1,1,1,1]]
result = model.predict(test)
final_result = le_result.inverse_transform(result)
print("Predicted Action:", final_result)


FileNotFoundError: [Errno 2] No such file or directory: '/x0dataset.csv'

#--**NAIVE BAYES**

In [5]:
def bayesrule(p_absent_and_friday,p_friday):
  return p_absent_and_friday/p_friday
p_absent_and_friday=0.03
p_friday=0.2
p_absent_and_friday=bayesrule(p_absent_and_friday,p_friday)
print("The probability that a student is absent given that today is Friday is :",p_absent_and_friday*100,"%")


The probability that a student is absent given that today is Friday is : 15.0 %


#--**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import random

data=load_iris()
label_target=data.target_names
print("Sample data from iris dataset")
print("*"*30)

for i in range(10):
  rn=random.randint(0,120)
  print(data.data[rn],"===>",label_target[data.target[rn]])

  x=data.data
  y=data.target
  x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
  print("The training dat aset length",len(x_train))
  print("The testing dat aset length",len(x_test))
  try:
    k=int(input("Enter the value of k:"))
    knn=KNeighborsClassifier(k)
    knn.fit(x_train,y_train)
    print("The Score is ",knn.score(x_test,y_test))
    test_data=input("Enter Test Data:").split(",")
    for i in range(len(test_data)):
      test_data[i]=float(test_data[i])
    print()
    v=knn.predict([test_data])
    print("Predicted output is ", label_target[v])
  except:
    print("Enter again")

Sample data from iris dataset
******************************
[6.7 3.1 4.7 1.5] ===> versicolor
The training dat aset length 105
The testing dat aset length 45
The Score is  0.9777777777777777

Predicted output is  ['setosa']
[4.4 2.9 1.4 0.2] ===> setosa
The training dat aset length 105
The testing dat aset length 45
The Score is  0.9777777777777777

Predicted output is  ['virginica']
[6.4 2.9 4.3 1.3] ===> versicolor
The training dat aset length 105
The testing dat aset length 45
The Score is  0.9777777777777777

Enter again
[5.8 4.  1.2 0.2] ===> setosa
The training dat aset length 105
The testing dat aset length 45


#--**K-Means**

In [ ]:
from sklearn.cluster import KMeans
import numpy as np

# Training data
X = np.array([
    [1.713, 1.586],
    [1.713, 1.586],
    [0.353, 1.240],
    [0.940, 1.286],
    [0.940, 1.566],
    [1.266, 1.106],
    [0.540, 0.419],
    [0.459, 1.799],
    [0.773, 0.186]
])

# Class labels
y = np.array([0, 1, 1, 0, 1, 0, 1, 1, 1])

# Create KMeans model
kmeans = KMeans(n_clusters=3, random_state=0)

# Fit the model
kmeans.fit(X, y)

print("The input data is")
print("VAR1 \t VAR2 \t CLASS")

i = 0
for val in X:
    print(val[0], "\t", val[1], "\t", y[i])
    i += 1

print("=" * 20)

# Get test data from user
print("The Test data to predict")
test_data = []

VAR1 = float(input("Enter value for VAR1: "))
VAR2=float(input("Enter Value of Var2"))
test_data.append(VAR1)
test_data.append(VAR2)
print("="*20)
print("The predicted class iss:",kmeans.predict([test_data]))